import Layout from '@/component/layout/Layout'
import BlogMain from '@/component/main/BlogMain'
import Head from 'next/head'
import React from 'react'

const blog = () => {
  return (
    <>
    <Head>
      <title>Blog</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="images/favicon.png" />
    </Head>
    <>
        <Layout>
            <BlogMain/>
        </Layout>
    </>
    </>
  )
}

export default blog