import FooterSection2 from '@/component/footer/FooterSection2'
import HeaderSection3 from '@/component/header/HeaderSection3'
import JewelleryShopMain from '@/component/main/JewelleryShopMain'
import Head from 'next/head'
import React from 'react'

const jewelleryShop = () => {
  return (
    <>
        <Head>
        <title>Farzaa - Jewellery Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="images/favicon.png" />
        </Head>
    <>
        <HeaderSection3/>
        <JewelleryShopMain/>
        <FooterSection2/>
    </>
    </>
  )
}

export default jewelleryShop