import ShopMainMill from '@/component/main/ShopMainMill'
import Head from 'next/head'
import React from 'react'
import Layout from '@/component/layout/Layout'

const millShop = () => {
  return (
    <>
    <Head>
      <title>Mill City Shop</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="images/favicon.png" />
    </Head>
    <>
      <Layout>
        <ShopMainMill/>
      </Layout> 
    </>
    </>
  )
}

export default millShop