import ShopMain from '@/component/main/ShopMain'
import Head from 'next/head'
import React from 'react'
import Layout from '@/component/layout/Layout'

const shop = () => {
  return (
    <>
    <Head>
      <title>Farzaa Shop</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="images/favicon.png" />
    </Head>
    <>
      <Layout>
        <ShopMain/>
      </Layout> 
    </>
    </>
  )
}

export default shop