import Layout from '@/component/layout/Layout'
import ShopDetailsMain from '@/component/main/ShopDetailsMain'
import Head from 'next/head'
import React from 'react'

const shopDetails = () => {
  return (
    <>
    <Head>
      <title>Farzaa Shop Details</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="images/favicon.png" />
    </Head>
    <>
      <Layout>
        <ShopDetailsMain/>
      </Layout> 
    </>
    </>
  )
}

export default shopDetails