import React from 'react'
import Layout from '@/component/layout/Layout'
import Head from 'next/head'
import SuccessMain from '@/component/main/SuccessMain'



const success = () => {
    return (
        <>
        <Head>
          <title>PrepMate</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="images/favicon.png" />
        </Head>
        <>
          <Layout>
          <SuccessMain/>
                <div style={{textAlign: 'center', marginTop: '100px', marginBottom: '100px'}}>
                    <h1>Thank You!</h1>
                    <p>Thank you for trusting PrepMate. Your order has successfully been received.</p>
                </div>          
          </Layout> 
        </>
        </>
      )
};

export default success;